name = :test

call test()	# Error 

func test